#!/bin/sh
set -e

if [ -z "$1" ]; then
	echo "Usage: $0 pdroid.diff"
	exit 1
fi

patchfile="$(readlink -f "$1")"

[ ! -d hunks ] || rmdir --ignore-fail-on-non-empty hunks
mkdir hunks
cd hunks
splitdiff -a -p1 -d "$patchfile"
rename 's/$/.patch/' *
