#!/bin/sh
set -e

outdir="${2:-hunks}"
prefix="$3"

if [ -z "$1" ]; then
	echo "Usage: $0 pdroid.diff [output dir] [patch filename prefix]"
	echo "If output dir is not given, 'hunks' is assumed."
	exit 1
fi

patchfile="$(readlink -f "$1")"

[ -d "$outdir" ] || mkdir "$outdir"
cd "$outdir"
splitdiff -a -p1 -d "$patchfile"

# add .patch suffix
for file in *; do
	if [ "${file%.patch}" = "${file}" ]; then
		sed -r '/^[^ -+@]/d' "$file" -i
		mv "$file" "$prefix$file.patch"
	fi
done
